name: Deploy Project
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
      - name: Update Controle Online
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.CONTROLEONLINE }}
          port: ${{ secrets.PORT }}
          script: |
                  export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"
                  cd ~/sistemas/controleonline/api/modules/controleonline/smoke-tests-playground
                  git fetch origin
                  git checkout master
                  git reset --hard origin/master
                  git clean -ffd
                  cd ~/sistemas/controleonline/api/
                  php bin/console cache:clear
